#python example
name : python

on:
 push:
  branches: labs
   

jobs:
 build:
  runs-on : ubuntu-latest
  
  steps:
  - name : checkout the code 
    uses : actions/checkout@v3
  - name : install python
    uses:  actions/setup-python@v4  
    with:
      python-version: '3.9'
  - name: install libraries
    run: |
     cd function
     python -m pip install upgrade pip
     if [ -f requirements.txt];
     then pip install -r requirements.txt . ;
     fi

