#python example
name : python

on:
 push:
  branches: labs
   

jobs:
 build:
  runs-on : [self-hosted, Linux, x64]
  
  steps:
  - name : checkout the code 
    uses : actions/checkout@v3
  - name : install python
    uses:  actions/setup-python@v4  
    with:
      python-version: '3.9'
  - name: install libraries
    run: |
     cd function
     python -m pip install --upgrade pip
     if [ -f requirements.txt];
     then pip install -r requirements.txt . ;
     fi
  - name: zip the bundle
    run: |
     cd function
     zip -r ../${{github.sha}}.zip .
     
  - name: archive artifact
    uses: actions/upload-artifact@v2
    with:
      name: zipped-bundle
      path: ${{github.sha}}.zip   


 publish :
  runs-on: ubuntu-latest
  needs: build
  steps:
   - name: create release
     uses: actions/create-release@v1
     env:  
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
     with:
      tag_name: ${{github.run_number}} 
      release_name: release from ${{github.run_number}}
      body:  new release for ${{github.sha}}
             release notes on documentation side.
      draft: false
      prerelease: false


